const katasData = [
  {
    title: "Make Counter",
    slug: "make-counter",
    description: "Implement a function *makeCounter* that accepts an optional interger value and returns a function that can be called to return the next integer value. The returned function *should* reset to 0 when it is called the first time or the value that is passed in the first time.",
    example: "const counter = makeCounter(5); counter(); // 5\ncounter(); // 6\ncounter(); // 7",
    language: "javaScript",
    difficulty: "Easy",
    topic: "",
  },
  {
    title: "Mean",
    slug: "mean",
    description: "Write a function that returns the mean of an array of numbers.\n\nThe function should return NaN if the array is empty.",
    example: "mean([1, 2, 3, 4]) // 2.5\n mean([6, 2, 1, 8]) // 4.25",
    language: "javaScript",
    difficulty: "Easy",
    topic: "",
  },
  {
    title: "Flatten",
    slug: "flatten",
    description: "Write a function *flatten* that returns a newly-created array with all sub-array elements concactenated recursively into a single level.",
    example: "const arr = [1, [2, 3], [4, [5, 6, [7, 8, 9]]], 10];\nflatten(arr); // [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]",
    language: "javaScript",
    difficulty: "Easy",
    topic: "",
  },
  {
    title: "Multiples of 3 or 5",
    slug: "multiples-of-3-or-5",
    description: "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\n\nFinish the solution so that it returns the sum of all the multiples of 3 or 5 **below** the number passed in. \n**Note:** If the number is a multiple of **both** 3 and 5, only count it *once*.",
    example: "function(20) should return 98 (3 + 5 + 6 + 9 + 10 + 12 + 15 + 18 + 20)",
    language: "javaScript",
    difficulty: "Medium",
    topic: "",
  },
  {
    title: "Digital Root",
    slug: "digital-root",
    description: "digital root is the _recursive sum of all the digits in a number._\n\nGiven `n`, take the sum of the digits of `n`. If that value has more than one digit, continue reducing in this way until a single-digit number is produced. The input will be a non-negative integer.",
    example: "16  -->  1 + 6 = 7\n   942  -->  9 + 4 + 2 = 15  -->  1 + 5 = 6\n132189  -->  1 + 3 + 2 + 1 + 8 + 9 = 24  -->  2 + 4 = 6\n493193  -->  4 + 9 + 3 + 1 + 9 + 3 = 29  -->  2 + 9 = 11  -->  1 + 1 = 2\n```\n",
    language: "javaScript",
    difficulty: "Medium",
    topic: "",
  },
  {
    title: "Create Stack",
    slug: "create-stack",
    description: "implement a data structure in javascript that contains the following operations.\n - push(value)\n - pop()\n - peek()\n - isEmpty()\n\nThe stack should be a class with methods `push`, `pop`, `peek` and `isEmpty`",
    example: "const stack = new Stack(); \nstack.push(1); \nstack.push(2); \nstack.push(3); \nstack.peek(); // 3\nstack.pop(); //3\nstack.peek(); // 2\n stack.isEmpty(); // false",
    language: "javaScript",
    difficulty: "Medium",
    topic: "",
  },
  {
    title: "Snail",
    slug: "snail",
    description: "Snail Sort\n\nGiven an `n x n` array, return the array elements arranged from outermost elements to the middle element, traveling clockwise.\n\n```\n",
    example: "array = [[1,2,3],\n         [4,5,6],\n         [7,8,9]]\nsnail(array) #=> [1,2,3,6,9,8,7,4,5]\n```\n\nFor better understanding, please follow the numbers of the next array consecutively:\n\n```\narray = [[1,2,3],\n         [8,9,4],\n         [7,6,5]]\nsnail(array) #=> [1,2,3,4,5,6,7,8,9]\n```",
    language: "javaScript",
    difficulty: "Medium",
    topic: "",
  },
  {
    title: "Pallindrome Counter",
    slug: "pallindrome-counter",
    description: "Background\n\nPalindromes are a special type of number (in this case a non-negative integer) that reads the same backwards as forwards. A number defined this way is called __palindromic__. \n\n* The following numbers are palindromes: `0`, `252`, `769967`, `1111111`. \n\n* The following numbers are __not__ palindromes: `123`, `689`, `565656`, `12345432`. \n\n# Problem Description\n\nIn this kata, you are required to build a function that receives two arguments, `a` and `b`, and returns the number of integer palindromes between `a` and `b` inclusive.",
    example: " If `a` is `6` and `b` is `11`, the function should output `5` because there are 5 palindromes between 6 and 11 inclusive: `6`, `7`, `8`, `9` and `11`. \n\ncounter(6, 11) // 5\n\n* If `a` is `150` and `b` is `250`, the function should output `10` because there are 10 palindromes between 150 and 250 inclusive: `151`, `161`, `171`, `181`, `191`, `202`, `212`, `222`, `232` and `242`.\n\ncounter(150, 250) // 10",
    language: "javaScript",
    difficulty: "Hard",
    topic: "",
  },
  {
    title: "Bake Cakes",
    slug: "bake-cakes",
    description: "You like to bake cakes. You have some recipes and ingredients. Write a function to quickly find out, if you have enough ingredients to bake a cake and how many of them.\n\nWrite a function `cakes()`, which takes the recipe (object) and the available ingredients (also an object) and returns the maximum number of cakes you can bake (integer). For simplicity there are no units for the amounts (e.g. 1 lb of flour or 200 g of sugar are simply 1 or 200). Ingredients that are not present in the objects, can be considered as 0.",
    example: "// must return 2\ncakes({flour: 500, sugar: 200, eggs: 1}, {flour: 1200, sugar: 1200, eggs: 5, milk: 200}); \n// must return 0\ncakes({apples: 3, flour: 300, sugar: 150, milk: 100, oil: 100}, {sugar: 500, flour: 2000, milk: 2000});",
    language: "javaScript",
    difficulty: "Hard",
    topic: "",
  },
 
];

export default katasData;
