import type { Metadata } from "next";
import "./globals.css";
import UserContextProvider from "./Context/UserProvider";
import Header from "./Header";
export const metadata: Metadata = {
  title: "Ace script",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Header />
          <main className="flex-1">{children}</main>
        </UserContextProvider>
      </body>
    </html>
  );
}
