import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import UserContextProvider from "./Context/UserProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body >
        <Header />
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );

}
